name: Check and Sync Node.js Versions

on:
  schedule:
    - cron: '0 0 * * *' # 每天 UTC 时间 00:00 运行
  push:
    branches:
      - bot # 当推送到 bot 分支时也触发

jobs:
  sync-node-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # 根据需要选择合适的 Node.js 版本

      - name: Install jq
        run: sudo apt-get install jq

      - name: Fetch Node.js versions released in the last 5 days and check npm
        run: |
          DATE_5_DAYS_AGO=$(date --date='5 days ago' +%Y-%m-%d)
          curl -s https://nodejs.org/dist/index.json | jq --arg DATE "$DATE_5_DAYS_AGO" -r '.[] | select(.date >= $DATE) | .version' > versions.txt
          while IFS= read -r VERSION; do
            if [ -z "$(npm view node@$VERSION version 2>/dev/null)" ]; then
              echo "Version $VERSION is not published on npm. Running custom script."
              mkdir -p "target/$VERSION" && cd "target/$VERSION"
              node ../../../index.js $VERSION
              npm publish
              cd ../../..
            else
              echo "Version $VERSION is already published on npm. Skipping."
            fi
          done < versions.txt
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
