name: Check and Sync Node.js Versions

on:
  schedule:
    - cron: '0 0 * * *' # 每天 UTC 时间 00:00 运行
  push:
    branches:
      - bot # 当推送到 bot 分支时也触发

jobs:
  sync-node-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # 选择一个合适的 Node.js 版本进行操作

      - name: Fetch Node.js versions released in the last 5 days
        run: |
          set -x
          DATE_5_DAYS_AGO=$(date --date='5 days ago' +%Y-%m-%d)
          curl -s https://nodejs.org/dist/index.json | jq --arg DATE "$DATE_5_DAYS_AGO" -r '.[] | select(.date >= $DATE) | .version' > versions.txt
          cat versions.txt
          set +x

      - name: Check each version and sync if not published
        run: |
          set -x
          while IFS= read -r VERSION; do
            echo "Checking version $VERSION..."
            if npm view node@$VERSION; then
              echo "Version $VERSION is already published on npm. Skipping."
            else
              echo "Version $VERSION is not published on npm. Running custom script."
              node ../../index.js $VERSION
              for dir in */ ; do
                if [ -d "$dir" ]; then
                  echo "Publishing directory: $dir"
                  cd "$dir"
                  npm publish
                  cd ..
                else
                  echo "Directory $dir not found."
                fi
              done
            fi
          done < versions.txt
          set +x
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
